-- MySQL Script generated by MySQL Workbench
-- 10/20/14 13:46:05
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema banco_estoque
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banco_estoque` DEFAULT CHARACTER SET latin1 ;
USE `banco_estoque` ;

-- -----------------------------------------------------
-- Table `banco_estoque`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_estoque`.`categorias` (
  `cat_id` INT NOT NULL AUTO_INCREMENT,
  `cat_titulo` VARCHAR(45) NOT NULL,
  `visivel` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`cat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_estoque`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_estoque`.`produtos` (
  `pro_id` INT NOT NULL AUTO_INCREMENT,
  `pro_titulo` VARCHAR(255) NOT NULL,
  `pro_descricao` TEXT NOT NULL,
  `pro_valor` DOUBLE NOT NULL,
  `pro_estoque` INT NOT NULL DEFAULT 0,
  `visivel` TINYINT(1) NOT NULL DEFAULT 1,
  `cat_id` INT NOT NULL,
  PRIMARY KEY (`pro_id`),
  INDEX `fk_produtos_categorias1_idx` (`cat_id` ASC),
  CONSTRAINT `fk_produtos_categorias1`
    FOREIGN KEY (`cat_id`)
    REFERENCES `banco_estoque`.`categorias` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_estoque`.`imagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_estoque`.`imagens` (
  `img_id` INT NOT NULL AUTO_INCREMENT,
  `pro_id` INT NOT NULL,
  `img_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`img_id`, `pro_id`),
  INDEX `fk_imagens_produtos1` (`pro_id` ASC),
  CONSTRAINT `fk_imagens_produtos1`
    FOREIGN KEY (`pro_id`)
    REFERENCES `banco_estoque`.`produtos` (`pro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_estoque`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_estoque`.`perfil` (
  `per_id` INT NOT NULL AUTO_INCREMENT,
  `per_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`per_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_estoque`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_estoque`.`clientes` (
  `cli_id` INT NOT NULL AUTO_INCREMENT,
  `cli_nome` VARCHAR(245) NOT NULL,
  `cli_login` VARCHAR(45) NOT NULL,
  `cli_senha` VARCHAR(255) NOT NULL,
  `cli_endereco` VARCHAR(255) NOT NULL,
  `cli_bairro` VARCHAR(45) NOT NULL,
  `cli_cidade` VARCHAR(150) NOT NULL,
  `cli_uf` CHAR(2) NOT NULL,
  `cli_cep` CHAR(10) NOT NULL,
  `cli_telefone` CHAR(14) NOT NULL,
  `per_id` INT NOT NULL,
  PRIMARY KEY (`cli_id`, `cli_login`),
  INDEX `fk_clientes_perfil1_idx` (`per_id` ASC),
  CONSTRAINT `fk_clientes_perfil1`
    FOREIGN KEY (`per_id`)
    REFERENCES `banco_estoque`.`perfil` (`per_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_estoque`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_estoque`.`vendas` (
  `ven_id` INT NOT NULL AUTO_INCREMENT,
  `cli_id` INT NOT NULL,
  `pro_id` INT NOT NULL,
  `pro_valor` VARCHAR(45) NOT NULL,
  `ved_qtd` INT NOT NULL,
  `ven_data` DATETIME NOT NULL,
  PRIMARY KEY (`ven_id`),
  INDEX `fk_vendas_clientes1` (`cli_id` ASC),
  INDEX `fk_vendas_produtos1` (`pro_id` ASC),
  CONSTRAINT `fk_vendas_clientes1`
    FOREIGN KEY (`cli_id`)
    REFERENCES `banco_estoque`.`clientes` (`cli_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendas_produtos1`
    FOREIGN KEY (`pro_id`)
    REFERENCES `banco_estoque`.`produtos` (`pro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
